"""Hợp đồng và hàm trích xuất đặc trưng URL dùng chung PhishGuard ML."""

from .contract import (
    FEATURE_COLUMNS,
    FEATURE_COLUMNS_V1,
    FEATURE_COLUMNS_V2,
    FEATURE_COLUMNS_V3,
    FEATURE_CONTRACT_V1,
    FEATURE_CONTRACT_V2,
    FEATURE_CONTRACT_V3,
    FEATURE_CONTRACT_VERSION,
)
from .extractor import (
    calculate_entropy,
    detect_brand_abuse,
    extract_features,
    extract_features_v1,
    extract_features_v2,
    first_directory_length,
    get_subdomain_and_labels,
    has_ip_address,
    has_punycode,
    has_redirection_pattern,
    parse_url,
    path_depth,
    tld_info,
    tld_length,
    uses_shortening_service,
)

__all__ = [
    "FEATURE_COLUMNS",
    "FEATURE_COLUMNS_V1",
    "FEATURE_COLUMNS_V2",
    "FEATURE_COLUMNS_V3",
    "FEATURE_CONTRACT_V1",
    "FEATURE_CONTRACT_V2",
    "FEATURE_CONTRACT_V3",
    "FEATURE_CONTRACT_VERSION",
    "calculate_entropy",
    "detect_brand_abuse",
    "extract_features",
    "extract_features_v1",
    "extract_features_v2",
    "first_directory_length",
    "get_subdomain_and_labels",
    "has_ip_address",
    "has_punycode",
    "has_redirection_pattern",
    "parse_url",
    "path_depth",
    "tld_info",
    "tld_length",
    "uses_shortening_service",
]
